from typing import Iterable, Tuple, List, Dict, Optional, Generator, Any

__all__ = (
    "Time",
    "Date",
    "DateTime",
    "Clock"
)

class Time:
    def __init__(self, seconds: float) -> None: ...
    @classmethod
    def from_units(cls, hours: int = 0, minutes: int = 0, seconds: float = 0.0) -> "Time": ...
    @classmethod
    def from_timestamp(cls, time: float) -> "Time": ...
    @classmethod
    def now(cls) -> "Time": ...
    @property
    def days(self) -> float: ...
    @days.setter
    def days(self, value: float) -> None: ...
    @property
    def hours(self) -> float: ...
    @hours.setter
    def hours(self, value: float) -> None: ...
    @property
    def minutes(self) -> float: ...
    @minutes.setter
    def minutes(self, value: float) -> None: ...
    @property
    def seconds(self) -> float: ...
    @seconds.setter
    def seconds(self, value: float) -> None: ...
    @property
    def microseconds(self) -> float: ...
    @microseconds.setter
    def microseconds(self, value: float) -> None: ...
    @property
    def milliseconds(self) -> float: ...
    @milliseconds.setter
    def milliseconds(self, value: float) -> None: ...
    @property
    def nanoseconds(self) -> float: ...
    @nanoseconds.setter
    def nanoseconds(self, value: float) -> None: ...
    @property
    def frozen(self) -> bool: ...
    def freeze(self) -> None: ...
    def to_units(self) -> Tuple[int, int, float]: ...


class Date:
    def __init__(self, year: int, month: int, day: int) -> None: ...
    @classmethod
    def from_timestamp(cls, time: float) -> "Date": ...
    @classmethod
    def today(cls) -> "Date": ...
    @property
    def year(self) -> int: ...
    @year.setter
    def year(self, value: int) -> None: ...
    @property
    def month(self) -> int: ...
    @month.setter
    def month(self, value: int) -> None: ...
    @property
    def day(self) -> int: ...
    @day.setter
    def day(self, value: int) -> None: ...
    @property
    def frozen(self) -> bool: ...
    def freeze(self) -> None: ...


class DateTime:
    def __init__(self, date: Date, time: Time) -> None: ...
    @classmethod
    def now(cls) -> "DateTime": ...
    @property
    def date(self) -> Date: ...
    @property
    def time(self) -> Time: ...


class Event:
    class Due:
        def __init__(self, date: Date, time: Time) -> None: ...
        @property
        def date(self) -> Date: ...
        @property
        def time(self) -> Time: ...
    def __init__(self, name: str, date: "Day.Date", time: Time, due: Optional["Event.Due"] = None) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def date(self) -> "Day.Date": ...
    @property
    def time(self) -> Time: ...
    @property
    def due(self) -> Optional["Event.Due"]: ...
    @property
    def duration(self) -> float: ...


class Day:
    class Date(Date):
        def __init__(self, year: int, month: int, day: int, day_object: "Day") -> None: ...
        def new_event(self, name: str, time: Time, due: Optional[Event.Due] = None) -> Event: ...
        def to_date(self) -> Date: ...
        @property
        def day_object(self) -> "Day": ...
    def __init__(self, name: str, year: int, month: int, day: int, week: Optional["Week"]) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def year(self) -> int: ...
    @property
    def month(self) -> int: ...
    @property
    def day(self) -> int: ...
    @property
    def week(self) -> Optional["Week"]: ...
    @property
    def date(self) -> "Day.Date": ...
    @property
    def events(self) -> List[Event]: ...
    def add(self, event: Event) -> None: ...
    def remove(self, event: Event) -> None: ...
    def clear(self) -> None: ...
    def new_event(self, name: str, date: "Day.Date", time: Time, due: Optional[Event.Due] = None) -> Event: ...
    def iterate(self) -> Generator[Event, Any, None]: ...
    def __iter__(self) -> Iterable[Event]: ...


class Week:
    def __init__(self, number: int, year: int, month: int, days: Optional[List[Day]] = None, month_object: Optional["Month"] = None) -> None: ...
    @property
    def month_object(self) -> Optional["Month"]: ...
    @property
    def number(self) -> int: ...
    @property
    def year(self) -> int: ...
    @property
    def month(self) -> int: ...
    @property
    def days(self) -> List[Day]: ...
    def add(self, day: Day) -> None: ...
    def remove(self, day: Day) -> None: ...
    def clear(self) -> None: ...
    def new_day(self, name: str, day: int) -> Day: ...
    def iterate(self) -> Generator[Day, Any, None]: ...
    def to_dict_name(self) -> Dict[str, Day]: ...
    def to_dict_day(self) -> Dict[int, Day]: ...
    def __iter__(self) -> Iterable[Day]: ...


class Month:
    def __init__(self, name: str, year: int, month: int, year_object: Optional["Year"] = None) -> None: ...
    @property
    def supposed_count(self) -> Tuple[int, int]: ...
    @property
    def year_object(self) -> Optional["Year"]: ...
    @property
    def name(self) -> str: ...
    @property
    def year(self) -> int: ...
    @property
    def month(self) -> int: ...
    @property
    def weeks(self) -> List[Week]: ...
    def add(self, week: Week) -> None: ...
    def remove(self, week: Week) -> None: ...
    def clear(self) -> None: ...
    def new_week(self, number: int, days: Optional[List[Day]] = None) -> Week: ...
    def iterate(self) -> Generator[Week, Any, None]: ...
    def __iter__(self) -> Iterable[Week]: ...


class Year:
    def __init__(self, year: int, months: Optional[List[Month]] = None) -> None: ...
    @property
    def is_leap(self) -> bool: ...
    @property
    def year(self) -> int: ...
    @property
    def months(self) -> List[Month]: ...
    def add(self, month: Month) -> None: ...
    def remove(self, month: Month) -> None: ...
    def clear(self) -> None: ...
    def new_month(self, name: str, month: int) -> Month: ...
    def iterate(self) -> Generator[Month, Any, None]: ...
    def to_dict_name(self) -> Dict[str, Month]: ...
    def to_dict_month(self) -> Dict[int, Month]: ...
    def __iter__(self) -> Iterable[Month]: ...


class Clock:
    def __init__(self, start: Optional[float] = None) -> None: ...
    @property
    def start_time(self) -> float: ...
    @property
    def day(self) -> int: ...
    @property
    def seconds(self) -> float: ...
    def now(self) -> float: ...
    @staticmethod
    def today() -> Date: ...
    @staticmethod
    def real_time() -> float: ...
    @staticmethod
    def new_time(seconds: float) -> Time: ...
    @staticmethod
    def due_date(date: Date, time: Time) -> Event.Due: ...
    @staticmethod
    def create_year(year: int, months: Optional[List[Month]] = None) -> Year: ...