from typing import Tuple, Dict, Callable, Optional, Any
from .core import Time, Clock as _Clock

class Callback:
    def __init__(self, target: Callable, args: Optional[Tuple] = None, kwargs: Optional[Dict[str, Any]] = None) -> None: ...
    def __call__(self) -> Any: ...


class Clock(_Clock):
    interval: int
    def __init__(self, start: Optional[float] = None) -> None: ...
    @property
    def callbacks_active(self) -> bool: ...
    def set_callback(self, time: Time, callback: Callback) -> None: ...
    def has_callback(self, time: Time) -> bool: ...
    def remove_callback(self, time: Time) -> None: ...
    def clear_callbacks(self) -> None: ...
    def start_schedule(self, daemon: bool = False) -> None: ...
    def update_schedule(self) -> None: ...
    def stop_schedule(self) -> None: ...
    def stop_thread(self, join_timeout: Optional[float] = None) -> None: ...
    def wait_for_scheduler(self) -> None: ...
    @staticmethod
    def new_callback(target: Callable, args: Optional[Tuple] = None, kwargs: Optional[Dict[str, Any]] = None) -> Callback: ...