from typing import (
    List, ParamSpec, TypeVar, Type, Generic, Callable, Union, Optional, Any
)

P = ParamSpec("P")
T = TypeVar("T")

class Environment:
    @property
    def start(self) -> float: ...
    @property
    def total_calls(self) -> int: ...
    @property
    def total_duration(self) -> float: ...
    @property
    def min_duration(self) -> float: ...
    @property
    def max_duration(self) -> float: ...
    @property
    def avg_duration(self) -> float: ...
    @property
    def history(self) -> List["Resolve"]: ...
    @property
    def methods(self) -> List["Method"]: ...
    def add(self, method: "Method") -> None: ...
    def remove(self, method: "Method") -> None: ...
    def clear(self) -> None: ...

class Resolve:
    def __init__(self, method: "Method", start: float, end: float, result: Any, exception: Optional[Exception] = None) -> None: ...
    @property
    def method(self) -> "Method": ...
    @property
    def start(self) -> float: ...
    @property
    def end(self) -> float: ...
    @property
    def duration(self) -> float: ... 
    @property
    def result(self) -> Any: ...
    @property
    def exception(self) -> Optional[Exception]: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __repr__(self) -> str: ...

class Method(Generic[P, T]):
    def __init__(self, method: Callable[P, T], *args: Any, **kwargs: Any) -> None: ...
    @property
    def name(self) -> Optional[str]: ...
    @property
    def doc(self) -> Optional[str]: ...
    @property
    def owner(self) -> Optional[Type]: ...
    @property
    def created_at(self) -> float: ...
    @property
    def resolve(self) -> Optional[Resolve]: ...
    @property
    def history(self) -> List[Resolve]: ...
    @property
    def avg_duration(self) -> float: ...
    @property
    def min_duration(self) -> float: ...
    @property
    def max_duration(self) -> float: ...
    @property
    def calls_per_second(self) -> float: ...
    @property
    def total_duration(self) -> float: ...
    @property
    def total_calls(self) -> int: ...
    def reset(self) -> None: ...
    def get_method(self) -> Callable[P, T]: ...
    def _record(self, resolve: Resolve) -> None: ...
    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> T: ...

class GlobalEnvironment:
    def __call__(self) -> Environment: ...

DecoratorLike = Callable[[Callable[P, T]], Method[P, T]]

def inspect(func: Optional[Callable[P, T]] = None, /, *args: Any, **kwargs: Any) -> Union[Method[P, T], DecoratorLike]: ...